server:
  port: 8080

spring:
  application:
    name: shop

  servlet:
    multipart:
      # 파일 한 개당 최대 사이즈
      max-file-size: 20MB
      # 요청당 최대 파일 크기
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: shopuser
    password: shoppassword

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    livereload:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: warn
      springframework:
        jdbc:
          datasource: warn

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha



# 상품 이미지 업로드 경로
itemImgLocation: "/app/uploads/item/"  # 컨테이너 내부 경로
